source/catalogue/index.md
=> Add GOV.UK Notify API

source/catalogue/index.md
Fix #4
@pauldougan , please double check we understood your input.
=> Add GOV.UK Platform as a Service (PaaS) API

source/catalogue/index.md
This PR fixes some markdown formatting issues, uses API names as headings to improve navigation and page structure and fixes: #5 (happy to raise this separately if requested).
[Preview the markdown changes](https://github.com/alphagov/api-catalogue/blob/fa17ab6bfe3aa8d703026d0b9b5f2eb90336acdb/source/catalogue/index.md)
=> Add govuk pay api

source/catalogue/index.md
=> Add Content API

source/central/dvla/authentication/index.html.md.erb, source/central/dvla/index.html.md.erb, source/central/dvla/vehicle-enquiry/index.html.md.erb, source/central/gds/bank-holidays/index.html.md.erb, source/local/London-Borough-Hackney/index.html.md.erb
This is a PR for #57 which was raised and merged into another branch than master.
Author @TechPunk316.
=> Add DVLA, London Borough of Hackney and Bank Holidays APIs

source/central/ea/index.html.md.erb, source/central/fsa/index.html.md.erb, source/central/gds/index.html.md.erb, source/central/ons/index.html.md.erb
PR #64 is stale. This recovers the improvements.
=> fix: Port PR #64 changes

source/central/ch/ch/index.html.md.erb, source/central/ch/streaming/index.html.md.erb, source/central/dvla/authentication/index.html.md.erb, source/central/dvla/vehicle-enquiry/index.html.md.erb, source/central/ea/flood/index.html.md.erb, source/central/gds/content/index.html.md.erb
Fixes more description headings that were out of alignment.
=> description heading fixes

.gitignore, .rspec, Gemfile, Gemfile.lock, spec/spec_helper.rb
[RSpec](https://rspec.info/) is a testing framework, which will enable us to write automated tests against our code. Eventually these tests can be part of the build process, giving us confidence to automatically deploy whatever changes are merged into `master` branch.
=> Setup RSpec testing framework

Gemfile, Gemfile.lock, spec/factories/api.rb, spec/lib/api_catalogue_spec.rb, spec/lib/dashboard_stats_spec.rb, spec/spec_helper.rb
This PR is a small tidy-up of the specs, introducing factories to make the specs clearer & easier to write tests in the future.
=> Add FactoryBot + factories

README.md
In the spirit of one change per PR, this is just to update the contact email address in README.md
=> update contact email

source/layouts/api_catalogue.erb
Updating domain in plausible snippet.
=> change domain in snippet

.dockerignore, Dockerfile, bin/docker_serve, docs/getting_started.md
Changes:
- Adds `Dockerfile` which sets up the project, with a default action of serving the site
- Adds a convenience script, `bin/docker_serve` to build the Docker image & run the container
- Updates 'Getting started' docs
=> Setup Docker

.github/workflows/ci.yml
Moving master to main broke this...
=> Update ci.yml to reflect default branch change

helpers/redirects/apim.html, helpers/redirects/apim/index.html, helpers/redirects/graphql.html, helpers/redirects/graphql/index.html, helpers/redirects/sc.html, helpers/redirects/sc/index.html
To automate the redirects on rebuild
=> add redirectes

README.md
Makes it look more clean.
Just to make it look a bit better.
Ik very stupid lol.
Keep safe!
=> Changed link text.

source/index.html.md
=> Clarify that not all APIs are public

source/resources/index.html.md, source/resources/links/index.html.md.erb
Updating index to match link name for API community links
=> Api links match

config/tech-docs.yml, source/index.html.md
=> Add a link to an API Survey to the home page

source/index.html.md
@RobNicholsGDS can we modify the text slightly so that we target gov and public sector employees?
=> Edit API Survey intro to target public sector employees

README.md
The data update had been made in https://github.com/co-cddo/api-catalogue-data-source
=> Small update to README to force rebuild.
