source/central/gds/dcs-pilot/index.html.md.erb, source/central/gds/index.html.md.erb
Bring the styling for the Document Checking Service (DCS) in line with [content on GOV.UK](https://www.gov.uk/guidance/apply-for-the-document-checking-service-pilot-scheme) and the [DCS pilot tech docs](https://dcs-pilot-docs.cloudapps.digital) by:
* removing the 'GOV.UK' prefix
* not capitalising 'pilot'
So product branding in the API Catalogue is consistent with content published on GOV.UK and other places like tech docs.
=> Bring Document Checking Service styling in line with GOV.UK

source/central/ea/flood/index.html.md.erb, source/central/ea/rain/index.html.md.erb, source/central/ea/tide/index.html.md.erb
I have changed the way that people can get more information from an email address to a link to the Defra Data Services Forum. This is the correct method to get additional support and information.
=> Updates to the Environment Agency API info

data/catalogue.csv-metadata.json, data/operational.csv-metadata.json, data/organisation.csv-metadata.json
This PR adds the three metadata files that describe the three sets of data that compose our initial data store:
* catalogue.csv: The set of Web API records provided by departments in government.
* organisation.csv: The set of Organisation records that we manage to classify ownership of catalogue records.
* operational.csv: The set of metadata used to operate the catalogue.
=> CSV on the Web metadata

source/central/gds/governments/index.html.md.erb, source/central/gds/world-locations/index.html.md.erb
Fix the documentation link on two GDS APIs, as per issue #72
=> fix link to documentation on world location and governments

source/central/ons/ons-stats/index.html.md.erb, source/central/ons/open-geog/index.html.md.erb
Markdown files for the ONS APIs were out of alignment and breaking description headers.
=> fix ONS Headings

Gemfile, Gemfile.lock, config.rb, source/stylesheets/print.css.scss, source/stylesheets/print.css.scss.erb, source/stylesheets/screen-old-ie.css.scss, source/stylesheets/screen-old-ie.css.scss.erb, source/stylesheets/screen.css.scss, source/stylesheets/screen.css.scss.erb
Changes:
- Configure Middleman to apply a `http_prefix` of `/api-catalogue/` when building (for Github Pages compatibility)
- Use absolute links & asset paths throughout (instead of relative)
- Switch to a branch of `tech-docs-gem` which adds `http_prefix` support (fixes Search, ToC, and asset paths)
Forms part of https://github.com/alphagov/api-catalogue/issues/95
=> Configure build for Github pages

.github/workflows/ci.yml, .gitignore, Gemfile, Gemfile.lock, Rakefile
The PR updates our CI workflow to:
1. Run tests via RSpec
1. Build the site
1. Deploy to Github pages (if the branch is `master`)
In summary, whenever a pull request is merged into `master`, a new version of the site will be deployed if there are any changes.
This functionally completes #95 (although we're still using a branch of `tech-docs-gem` until upstream PRs are merged)
=> Automate publishing to Github pages

config.rb, source/layouts/api_catalogue.erb
Adding to the `<head>` element because this is currently the only part of the tech-docs-gem layout which yields for extra content. There should be almost no performance impact from this `<head>` placement (vs. before `</body>`) because it uses defer/async.
References:
- https://plausible.io/
=> Add Plausible Analytics

.git-blame-ignore-revs, .github/workflows/ci.yml, .rubocop.yml, Gemfile, Gemfile.lock, Rakefile, config.rb, lib/api_catalogue.rb, lib/dashboard_stats.rb, lib/url_helpers.rb, spec/lib/api_catalogue_spec.rb, spec/lib/dashboard_stats_spec.rb
This PR adopts the [GOV.UK code formatting rules for Ruby](https://gds-way.cloudapps.digital/manuals/programming-languages/ruby.html#code-formatting).
Changes:
- Adds Rubocop (a Ruby code linter) configured with the [GOV.UK Rubocop rules](https://github.com/alphagov/rubocop-govuk)
- Corrects existing code to match the rules
- Adds a linting step to our GitHub Actions workflow, to ensure each PR keeps to the rules
- Configure the default Rake task to run specs (with RSpec) and lint (with Rubocop)
=> Adopt GOV.UK Ruby style

helpers/format_helpers.rb, source/api_details.html.erb, spec/helpers/format_helpers_spec.rb
This PR renders any markdown in the API descriptions, and converts any escaped newlines into actual newline characters before conversion (so two consecutive newlines will result in a new paragraph, as per standard Markdown formatting).
Part of https://github.com/alphagov/api-catalogue/issues/89
This PR does **not** address data issues where newlines are encoded incorrectly (we've seen `-n` and `/n`). I'll make a follow-up PR to clean the data itself rather than handle this in code.
=> Render markdown + unescape newlines in API descriptions

Rakefile, config.rb, config/tech-docs.yml, source/accessibility.html.md.erb, source/stylesheets/print.css.scss, source/stylesheets/print.css.scss.erb, source/stylesheets/screen-old-ie.css.scss, source/stylesheets/screen-old-ie.css.scss.erb, source/stylesheets/screen.css.scss, source/stylesheets/screen.css.scss.erb
Config changes for https://github.com/alphagov/api-catalogue/issues/111 - moving from the Github pages URL (https://alphagov.github.io/api-catalogue) to a custom domain (https://www.api.gov.uk)
Summary:
- Remove `http_prefix` related settings required for serving site of GH pages default domain
- Undo customisation of GOV.UK frontend assets path required for GH pages default domain
- Update references to outgoing URL
=> Adjust config for new domain

Rakefile
This is small config change to ensure the `CNAME` file on the `gh-pages` branch doesn't get removed by the `publish` Rake task (currently this issue results in the custom domain setting being removed as we publish, which is a bug).
=> Ensure CNAME config is kept on gh-pages branch

adr/0001-remove-tech-docs-gem-dependency.md, adr/template.md
Template is based off the Architecture decision record template by Michael Nygard:
https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md
Except the status (& dates) are stored in front-matter for easy programmatic access in the future (Github renders these as a table by default).
=> Add ADR for Removal of the TDG

package-lock.json, package.json
Resolves 3 NPM audit issues:
- https://npmjs.com/advisories/328
- https://npmjs.com/advisories/796
- https://npmjs.com/advisories/1518
Ran migration plugins noted here, no changes were proposed:
https://jquery.com/upgrade-guide/3.0/#jquery-migrate-plugin
---
Upgrading major versions of jQuery doesn't reveal any incompatibilities with our JavaScript, or other 3rd party libraries, but it does change the supported browsers. From the upgrade guide:
> # Browser Support
> As of jQuery 3.0, the following browsers are supported:
> -  Internet Explorer: 9+
>  - Chrome, Edge, Firefox, Safari: Current and Current - 1
> - Opera: Current
> - Safari Mobile iOS: 7+
> - Android 4.0+
Whereas version `1.x` supported IE 6, 7, 8.
I think it's worth upgrading to keep on a version with security updates, but it …
=> Upgrade jquery from 1.12.4 to 3.5.1

source/accessibility.html.md.erb
We will not be able to fix the accessibility related issues for the tech docs template by the end of 2020.
We are extending the date to end of March 2021. Hopefully by that point we will have some developer resource to look at these issues.
=> Update tech docs template date to March 2021

data/catalogue.csv-metadata.json
JSON-LD requires `\` to be escaped ad `\\`.
=> Fix regex escape sequences

source/overview_index.html.erb
Following the changes in https://github.com/alphagov/api-catalogue/pull/218, this fixes the nav name for the 'A to Z' page so it matches the new page title.
=> Fix A to Z title so it matches page title

.github/workflows/ci.yml, Gemfile, Gemfile.lock, Rakefile, config.rb, data/links.csv, lib/links.rb, lib/links/link.rb, lib/links/links.rb, lib/url_helpers.rb, source/resources/index.html.md, source/resources/links/feed.xml.builder, source/resources/links/index.html.md.erb, spec/lib/url_helpers_spec.rb
To better serve the X-Government API community - in-and-out of our Slack
community - as well as providing some interesting resources for the
private sector, we should publish our interesting links publicly.
This produces both an HTML frontend and an RSS feed, so folks have
options for keeping up-to-date on what's available and being published.
This requires a new CSV data source, and:
- we can utilise the `builder` gem to more easily build up our Atom
(RSS) feed
- we make sure to add `rel=alternate` to allow for automagic detection
by feed readers
- add a new `Link` + `Links` class to contain the ?.
- add validation through Active Model for the `Link` class, to perform
batteries-included validation
- add a Rake task to validate that the link data is well-formed, with a
`schema` namespace …
=> Add archive for interesting resources and links

source/resources/links/index.html.md.erb
- Don't use title case for `h1`s
- Use `h2`s for additional headers
=> Amend API Links page for better accessibility

source/resources/links/feed.xml.builder
As well as the tracking URL utilised in the body of the entry, we should
also make the `rel=alternate` a tracking URL, which is likely to be the
primary link used by subscribers.
=> Use tracking URLs in feeds

.github/workflows/ci.yml
Fix for 188842b9ce16ce30eac7aefe99b7daaf54b8f593, as `setup-ruby` needs
to know from the contents of the `.ruby-version` file.
=> Fix: Add checkout before `setup-ruby`

.github/workflows/ci.yml
As our Rake tasks expect it to be there.
Fixup for 188842b9ce16ce30eac7aefe99b7daaf54b8f593.
=> Fix: Download built site to the `build` directory

.github/dependabot.yml, .github/workflows/ci.yml, CODEOWNERS
This addresses some of the [guidance GDS has on using Github Actions](https://gds-way.cloudapps.digital/standards/source-code.html#using-github-actions-and-workflows), and the warnings flagged by the scorecards security check, specifically:
- Pinning actions to a specific version
- Using a CODEOWNERS file to protect the .github/workflows folder
- Setting top level permissions for workflows
- Adding a dependabot configuration
=> GitHub actions best practices

.github/ISSUE_TEMPLATE/new-catalogue-entry-request.md, README.md, bin/docker_serve, config/tech-docs.yml, data/catalogue.csv-metadata.json, docs/getting_started.md
Although GitHub applies the redirect for us, we should make sure that
we're still sending people to the correct location, which is on the new
organisation.
=> Ensure co-cddo organisation is reference for this repo

lib/fetcher/v1_alpha_fetcher.rb, spec/lib/v1_alpha_fetcher_spec.rb
We want to remove it to create the contracted version, but not change the name
that's actually displayed in the contents.
=> Ensure the word 'and' isn't removed from the display name

source/api_details.html.erb
During user research we found that the first thing people wanted to see was a
summary of what the API is, it's purpose and what you've got from it, and how
to get authentication. To meet these expectations this moves the description
and licence information to the top of the page.
=> Re-order the API pages layout

source/layouts/_footer.erb, source/layouts/core.erb, source/resources/index.html.md
We don't want the resources link to be at the top of the navigation bar as it's
not part of the typical user journey, so these have been moved down to the
footer.
We've also removed the `View source` link as this doesn't work as expected and
isn't useful.
The 'Report a problem with this page' link is still in the page content above the footer,
as this is page-specific and we think the footer should contain links that are consistent across
the site.
We are planning to convert the 'Supporting resources' page into a communities page, with links through to the links and other pages in future.
=> Update the footer content

Dockerfile
We were seeing the following error when running the Docker build: `LoadError:
Could not open library 'libcurl': Error loading shared library libcurl: No such
file or directory.`
The `html-proofer` gem depends on `typhoeus` which in turn depends on
`libcurl`, which needs `curl` to be installed. `curl` isn't automatically
included in Alpine Docker images so we need to add it manually.
=> Add curl to Docker build

data/registry_entries.csv
We've changed the default branch for the data source repo, so we need to update it here too
=> Update URL for the FSA endpoint

.gitignore, config.rb, lib/provider.rb, lib/provider/v1_alpha_provider.rb, spec/lib/test_data/all_apis.json, spec/lib/test_data/all_apis_multiple_catalogues.json, spec/lib/v1_alpha_provider_spec.rb
This means that other catalogues will be able to consume this catalogue using
our federated model of data discovery:
https://github.com/co-cddo/federated-api-model/blob/arnau-handover/design/artefacts/system-context.svg
As this is a static site we don't currently have storage for apis, so this is
slightly different to our model.
Also as this is a static site, to create the 'endpoint' we create a temporary
file that gets copied to the build folder.
For the tests we're comparing the parsed json rather than the raw json strings,
as this allows us to store the expected result in a separate formatted json
file which is more readable, and allows us to compare the actual values.
We're only using this for apis we ingest using the federated model, as we know
these ones follow our schema.
=> Add an endpoint for all apis found with federated model

lib/provider/v1_alpha_provider.rb, spec/lib/test_data/all_apis.json, spec/lib/test_data/all_apis_multiple_catalogues.json, spec/lib/v1_alpha_provider_spec.rb
The structure of the endpoint was slightly wrong, this corrects that
so that it can be consumed by other catalogues.
It also fixes an issue with displaying the organisation in the tests.
=> Update JSON endpoint

.github/workflows/scorecards-analysis.yml
Some of the dependencies in this workflow are out of date. We're also seeing the scorecards workflow fail:
https://github.com/co-cddo/api-catalogue/actions/runs/3146676057
This suggests adding the id-token permission might fix it:
https://github.com/ossf/scorecard-action/issues/900
=> Update scorecards workflow dependencies

docs/getting_started.md
Token has been deleted - so is no longer valid
=> Fix a very stupid error in README where scorecard url being token.

package-lock.json, package.json, yarn.lock
This reverts commit b4c586d5bbc6fefdfd4bb58d99d2ea8f7fdd84df. as I appears to have broken the site's styling
=> Revert "Bump govuk-frontend from 4.7.0 to 4.8.0"

README.md, data/catalogue-from-json-source.csv
It can be awkward to compare the data held locally within data/catalogue.csv and that held in the remote https://github.com/co-cddo/api-catalogue-data-source JSON files. So the JSON data has been gathered and put into a local CSV file so that it is easier to compare.
=> Add CSV containing data held in remote JSON files

source/index.html.md
With this update the home page looks like this:
=> Remove references to CDDO and scope of project description on home page

README.md, config.rb, data/catalogue.csv, data/organisation.csv
- Use data in catalogue-from-json-source CSV to populate catalogue.csv with remote data
This change has been initiated due to one of the remote sources becoming unreachable due to a site certification issue.
The presence of the JSON source data was a proof of concept that is no longer relevant, and having two data sources just adds unnecessary complication.
=> Remove pull of data from remote JSON source.
